In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')

In [3]:
df_test = pd.read_csv('test.csv')

In [12]:
df_train

allelectrons_Total  density_Total  allelectrons_Average  val_e_Average  \
0                   100.0       0.841611             10.000000       4.800000   
1                   100.0       7.558488             10.000000       4.800000   
2                    76.0       8.885992             15.600000       5.600000   
3                   100.0       8.795296             10.000000       4.800000   
4                   116.0       9.577996             11.600000       4.800000   
...                   ...            ...                   ...            ...   
10402               128.0       7.558488             12.000000       4.000000   
10403                30.0       1.743160             10.000000       5.333333   
10404               196.0      30.920000             24.500000       5.500000   
10405                38.0       1.553160             12.666667       4.666667   
10406               288.0      24.655328             11.142857       4.571429   

       atomicweight_Average  ionenergy_Average  el_neg_chi_Average  \
0                 20.612526          11.088100            2.766000   
1                 20.298893          12.040830            2.755000   
2                 33.739258          12.086300            2.828000   
3                 20.213349          10.948500            2.648000   
4                 24.988133          11.824480            2.766000   
...                     ...                ...                 ...   
10402             26.385218          11.330440            2.644000   
10403             20.766935          14.163933            3.090000   
10404             53.490297          10.074300            2.295000   
10405             26.621687          11.290033            2.743333   
10406             22.536126          10.960357            2.792143   

       R_vdw_element_Average  R_cov_element_Average  zaratio_Average  \
0                   1.732000               0.860000         0.496070   
1                   1.631000               0.910000         0.492719   
2                   1.788000               0.864000         0.481478   
3                   1.626000               0.936000         0.489272   
4                   1.682000               0.896000         0.492736   
...                      ...                    ...              ...   
10402               1.631000               0.892000         0.496070   
10403               1.556667               0.866667         0.480390   
10404               1.545000               1.120000         0.469715   
10405               1.756667               0.980000         0.486507   
10406               1.772857               0.940000         0.493919   

       density_Average  Hardness  
0              0.91457       6.0  
1              0.71760       6.5  
2              1.50633       2.5  
3              0.78937       6.0  
4              1.86481       6.0  
...                ...       ...  
10402          1.79607       4.0  
10403          0.81480       5.0  
10404          2.11540       1.8  
10405          0.77755       6.0  
10406          0.97737       6.5  

[10407 rows x 12 columns]

In [13]:
df_test

allelectrons_Total  density_Total  allelectrons_Average  val_e_Average  \
0                  884.0     121.420000             35.360000       5.280000   
1                   90.0       9.931960             18.000000       5.600000   
2                  116.0       7.767992             11.600000       4.800000   
3                  100.0       9.107996             10.000000       4.800000   
4                   55.0       4.030000             11.000000       4.000000   
...                  ...            ...                   ...            ...   
6934               446.0      36.135392              9.636364       4.636364   
6935                36.0       3.550000             18.000000       4.000000   
6936                68.0       4.545328             11.333333       5.333333   
6937                40.0       2.334164              6.666667       4.000000   
6938               134.0      17.590000             67.000000       5.000000   

      atomicweight_Average  ionenergy_Average  el_neg_chi_Average  \
0                82.561240           9.370384            2.298000   
1                39.568056          12.086300            2.868000   
2                23.231818          11.023840            2.644000   
3                20.298893          12.086300            2.828000   
4                22.977675          11.280950            2.455000   
...                    ...                ...                 ...   
6934             19.689448          11.045515            2.768636   
6935             36.068500           8.236600            1.790000   
6936             22.688853          10.938358            2.876667   
6937             13.016128          12.700467            2.770000   
6938            167.400000           8.213150            1.950000   

      R_vdw_element_Average  R_cov_element_Average  zaratio_Average  \
0                  1.907200               1.200000         0.461899   
1                  1.652000               0.864000         0.476196   
2                  1.794000               0.960000         0.499514   
3                  1.662000               0.792000         0.495796   
4                  1.750000               0.893333         0.476095   
...                     ...                    ...              ...   
6934               1.769697               0.871818         0.498702   
6935               2.055000               1.390000         0.499000   
6936               1.713333               0.916667         0.499074   
6937               1.476667               0.616667         0.663797   
6938               2.040000               1.410000         0.401635   

      density_Average  
0             1.79459  
1             1.41194  
2             0.78834  
3             1.20466  
4             0.93456  
...               ...  
6934          0.11548  
6935          1.35045  
6936          0.73425  
6937          0.51227  
6938          0.44035  

[6939 rows x 11 columns]

In [14]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10407 entries, 0 to 10406
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   allelectrons_Total     10407 non-null  float64
 1   density_Total          10407 non-null  float64
 2   allelectrons_Average   10407 non-null  float64
 3   val_e_Average          10407 non-null  float64
 4   atomicweight_Average   10407 non-null  float64
 5   ionenergy_Average      10407 non-null  float64
 6   el_neg_chi_Average     10407 non-null  float64
 7   R_vdw_element_Average  10407 non-null  float64
 8   R_cov_element_Average  10407 non-null  float64
 9   zaratio_Average        10407 non-null  float64
 10  density_Average        10407 non-null  float64
 11  Hardness               10407 non-null  float64
dtypes: float64(12)
memory usage: 975.8 KB


In [15]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6939 entries, 0 to 6938
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   allelectrons_Total     6939 non-null   float64
 1   density_Total          6939 non-null   float64
 2   allelectrons_Average   6939 non-null   float64
 3   val_e_Average          6939 non-null   float64
 4   atomicweight_Average   6939 non-null   float64
 5   ionenergy_Average      6939 non-null   float64
 6   el_neg_chi_Average     6939 non-null   float64
 7   R_vdw_element_Average  6939 non-null   float64
 8   R_cov_element_Average  6939 non-null   float64
 9   zaratio_Average        6939 non-null   float64
 10  density_Average        6939 non-null   float64
dtypes: float64(11)
memory usage: 596.4 KB


In [16]:
df_train.isna().sum()

allelectrons_Total       0
density_Total            0
allelectrons_Average     0
val_e_Average            0
atomicweight_Average     0
ionenergy_Average        0
el_neg_chi_Average       0
R_vdw_element_Average    0
R_cov_element_Average    0
zaratio_Average          0
density_Average          0
Hardness                 0
dtype: int64

In [17]:
df_test.isna().sum()

allelectrons_Total       0
density_Total            0
allelectrons_Average     0
val_e_Average            0
atomicweight_Average     0
ionenergy_Average        0
el_neg_chi_Average       0
R_vdw_element_Average    0
R_cov_element_Average    0
zaratio_Average          0
density_Average          0
dtype: int64

In [11]:
df_train = df_train.drop('id', axis = 1)
df_test = df_test.drop('id', axis = 1)

In [18]:
X = df_train.drop('Hardness', axis=1)
y = df_train['Hardness']

In [35]:
from sklearn.model_selection import train_test_split

In [291]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.671, random_state=42)

In [292]:
from sklearn.linear_model import LinearRegression

In [293]:
model = LinearRegression()

In [294]:
model.fit(X_train, y_train)

LinearRegression()

In [295]:
y_pred = model.predict(X_test)

In [296]:
y_pred

array([5.38928183, 4.96064885, 4.21150051, ..., 4.72317067, 5.36133637,
       3.97934936], shape=(6984,))

In [297]:
from sklearn.metrics import mean_squared_error

In [298]:
mean_squared_error(y_test, y_pred)

2.14412522703756

In [44]:
from sklearn.tree import DecisionTreeRegressor

In [45]:
model = DecisionTreeRegressor()

In [46]:
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [47]:
y_pred1 = model.predict(X_test)

In [48]:
y_pred1

array([5.5, 6. , 2.3, ..., 6. , 5.5, 3.8], shape=(3123,))

In [56]:
mean_squared_error(y_test, y_pred1)

3.024610822926673

In [50]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [51]:
scaler = StandardScaler()

In [52]:
X_std_scaler = scaler.fit_transform(X)

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X_std_scaler, y, test_size=0.3, random_state=42)

In [54]:
model = DecisionTreeRegressor()

In [55]:
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [57]:
y_pred2 = model.predict(X_test)

In [59]:
y_pred2

array([5. , 6. , 2.5, ..., 6. , 5.5, 3.8], shape=(3123,))

In [58]:
mean_squared_error(y_test, y_pred2)

2.952868908101185

In [60]:
scaler = MinMaxScaler()

In [61]:
X_minmax_scaler = scaler.fit_transform(X)

In [142]:
X_train, X_test, y_train, y_test = train_test_split(X_minmax_scaler, y, test_size=0.7, random_state=42)

In [143]:
model = DecisionTreeRegressor()

In [144]:
model.fit(X_train, y_train)

DecisionTreeRegressor()

In [145]:
y_pred3 = model.predict(X_test)

In [66]:
y_pred3

array([5. , 6. , 2.5, ..., 6. , 5.5, 3.5], shape=(3123,))

In [67]:
mean_squared_error(y_test, y_pred3)

3.0387962215818125

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [115]:
model = DecisionTreeRegressor()
scaler = StandardScaler()

In [116]:
from sklearn.pipeline import Pipeline

In [117]:
pipe = Pipeline([('scaler', scaler), ('model', model)])

In [118]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', DecisionTreeRegressor())])

In [119]:
y_pred4 = pipe.predict(X_test)

In [76]:
y_pred4

array([5. , 6. , 2.5, ..., 6. , 5.5, 3.5], shape=(3123,))

In [77]:
mean_squared_error(y_test, y_pred4)

3.1146255523535062

In [271]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.671, random_state=42)

In [272]:
model = DecisionTreeRegressor()
scaler = StandardScaler()

In [273]:
pipe = Pipeline([('scaler', scaler), ('model', model)])

In [274]:
model_params = {
    "model__criterion" : ["squared_error", "friedman_mse", "absolute_error", "poisson"],
    "model__splitter" : ["best", "random"],
    "model__max_depth": [None, 2, 6, 10]
}

In [275]:
from sklearn.model_selection import GridSearchCV

In [276]:
final_model = GridSearchCV(pipe, param_grid=model_params, cv=5, verbose=2)

In [277]:
final_model.fit(X_train, y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV] END model__criterion=squared_error, model__max_depth=None, model__splitter=best; total time=   0.0s
[CV] END model__criterion=squared_error, model__max_depth=None, model__splitter=best; total time=   0.0s
[CV] END model__criterion=squared_error, model__max_depth=None, model__splitter=best; total time=   0.0s
[CV] END model__criterion=squared_error, model__max_depth=None, model__splitter=best; total time=   0.0s
[CV] END model__criterion=squared_error, model__max_depth=None, model__splitter=best; total time=   0.0s
[CV] END model__criterion=squared_error, model__max_depth=None, model__splitter=random; total time=   0.0s
[CV] END model__criterion=squared_error, model__max_depth=None, model__splitter=random; total time=   0.0s
[CV] END model__criterion=squared_error, model__max_depth=None, model__splitter=random; total time=   0.0s
[CV] END model__criterion=squared_error, model__max_depth=None, model__splitter=random; tota

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', DecisionTreeRegressor())]),
             param_grid={'model__criterion': ['squared_error', 'friedman_mse',
                                              'absolute_error', 'poisson'],
                         'model__max_depth': [None, 2, 6, 10],
                         'model__splitter': ['best', 'random']},
             verbose=2)

In [278]:
final_model.best_score_

np.float64(0.34714040562748555)

In [279]:
final_model.best_estimator_

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', DecisionTreeRegressor(max_depth=6))])

In [280]:
y_pred5 = final_model.predict(X_test)

In [281]:
y_pred5

array([5.59982505, 4.82323232, 2.95652174, ..., 4.3322314 , 5.59982505,
       4.11573034], shape=(6984,))

In [286]:
y_pred5

array([5.59982505, 4.82323232, 2.95652174, ..., 5.59982505, 2.75636364,
       3.16153846], shape=(6939,))

In [287]:
sub = pd.read_csv('sample_submission.csv')

In [288]:
sub

id  Hardness
0     10407     4.647
1     10408     4.647
2     10409     4.647
3     10410     4.647
4     10411     4.647
...     ...       ...
6934  17341     4.647
6935  17342     4.647
6936  17343     4.647
6937  17344     4.647
6938  17345     4.647

[6939 rows x 2 columns]

In [289]:
sub['Hardness'] = y_pred5

In [290]:
sub.to_csv('submit.csv', index = False, index_label = False)

In [299]:
y_pred

array([5.38928183, 4.96064885, 4.21150051, ..., 4.72317067, 5.36133637,
       3.97934936], shape=(6984,))

In [302]:
sub['Hardness'] = y_pred

In [303]:
sub.to_csv('sub.csv', index = False, index_label = False)